In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#19.

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([7,8])
arr3 = np.concatenate((arr1,arr2.reshape(1,2)),axis =0)
print(arr3)

[[1 2]
 [3 4]
 [7 8]]


In [3]:
#21.

def integer_array(start,end,step):
    return np.arange(start,end+1,step)

arr = integer_array(2,10,2)
arr

array([ 2,  4,  6,  8, 10])

In [4]:
#22.

def equally_spaced_array(start,end,num):
    return np.linspace(start,end,num)

arr = equally_spaced_array(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
#23.

def log_spaced(start, end, num):
    return np.logspace(np.log10(start),np.log10(end),num)

arr = log_spaced(1,1000,5)
arr

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [6]:
#24.

np.random.seed(30)
data = np.random.randint(1,100,(5,3))
df = pd.DataFrame(data)
df

0   1   2
0  38  38  46
1  46  13  24
2   3  54  18
3  47   4  42
4   8  66  50

In [7]:
#26.

arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [8]:
#27.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [9]:
#28.

arr = np.array([3, 8, 2, 10, 5, 7])
s = arr > 5
print(s)

[False  True False  True False  True]


In [10]:
#29.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
r = arr[2:6]
print(r)

[3 4 5 6]


In [11]:
#30.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
p = arr_2d[0:2,1:]
print(p)

[[2 3]
 [5 6]]


In [12]:
#32.

def greater_array(arr,threshold):
    boolean = arr > threshold
    filtered = arr[boolean]
    return filtered

arr = np.array([1,3,6,7,5,8,9,4])
threshold = 3
filtered = greater_array(arr,threshold)
print(filtered)

[6 7 5 8 9 4]


In [13]:
#34.

def filtered_elements(arr, condtn1,condtn2):
    m1 = condtn1(arr)
    m2 = condtn2(arr)
    logic = m1 & m2
    filter_array = arr[logic]
    return filter_array


arr = np.array([1,2,3,4,5,6,7,8,10])

def condtn1(x):
    return x > 2
def condtn2(x):
    return x % 2 == 0

filter_array = filtered_elements(arr,condtn1,condtn2)
print(filter_array)

[ 4  6  8 10]


In [14]:
#35.

def extract_element(arr,rows,cols):
    return arr[rows,cols]

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = np.array([0,1,2])
cols = np.array([2,2,1])
arr1 = extract_element(arr,rows,cols)
print(arr1)    

[3 6 8]


In [15]:
#36.

arr = np.zeros((3,3))
arr + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [16]:
#37.

arr1 = np.random.randint(1,5,(1,3))
arr2 = np.random.randint(1,5,(3,4))
arr3 = np.reshape(arr1,(3,))
print(arr3[:,np.newaxis] * arr2)

[[ 6  6  2  2]
 [ 6  2  2  6]
 [12 16 12  8]]


In [17]:
#38.

arr1 = np.random.randint(1,5,(1,4))
arr2 = np.random.randint(1,5,(4,3))


arr3 = np.reshape(arr1,(4,))

print(arr3[:,np.newaxis] + arr2)

[[5 2 3]
 [6 5 7]
 [5 6 7]
 [8 7 6]]


In [18]:
#39.

arr1 = np.random.randint(1,5,(3,1))
arr2 = np.random.randint(1,5,(1,3))


arr3 = np.reshape(arr2,(3,))

print(arr3 + arr1[:,np.newaxis])

[[[3 2 3]]

 [[6 5 6]]

 [[6 5 6]]]


In [19]:
#40.

arr1 = np.random.randint(1,5,(2,3))
arr2 = np.random.randint(1,5,(2,2))

print(arr1 * arr2[:, :, np.newaxis])

[[[16  8 16]
  [ 8  8  4]]

 [[ 4  2  4]
  [ 6  6  3]]]


In [20]:
#41.

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [21]:
#42.

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)

array([3, 6])

In [22]:
#43.

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr,axis=0)

array([1, 1, 1])

In [23]:
#45.


arr = np.array([[2, 4, 6], [3, 5, 7]])

even = np.all(arr%2==0,axis=0)
if np.all(even):
    print('all element in each column are even')
else:
    print("not all elements in each column are even")

not all elements in each column are even


In [24]:
#46.

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped = np.reshape(original_array,(2,3))
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#47.
def flatten_mat(mat):
    return mat.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
arr = flatten_mat(input_matrix)
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
#48.

def concatenate_arr(arr1,arr2,axis=0):
    return np.concatenate((arr1,arr2),axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
r1 = concatenate_arr(array1,array2,axis = 0)
r2 = concatenate_arr(array1,array2,axis = 1)

print(r1)
print(r2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [27]:
#51.

arr1 = np.random.rand()
arr2 = np.random.randint(1,10)
print(arr1 + arr2)
print(arr1)
print(arr2)

7.15681568885132
0.15681568885132013
7


In [28]:
#52.

arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)

arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [29]:
#53.

arr1 = np.random.rand()
arr2 = np.random.randint(1,5)

arr1*arr2

0.7723041769136947

In [30]:
#54.

arr1 = np.arange(2,11,2)
arr2 = np.random.randint(1,5)
arr1/arr2

array([1., 2., 3., 4., 5.])

In [31]:
#55.

arr1 = np.arange(1,5)
arr2 = np.flip(arr1)
exp = np.exp(arr1**arr2)

In [32]:
exp

array([2.71828183e+00, 2.98095799e+03, 8.10308393e+03, 5.45981500e+01])

In [33]:
#59.

def concatenate_strings(arr1,arr2):
    return np.array([' '.join(pair) for pair in zip(arr1,arr2)])

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
s = concatenate_strings(arr1,arr2)
print(s)

['Hello Open' 'World AI']


In [34]:
#61.

data = np.random.randint(1,1000,100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(mean)
print(median)
print(variance)
print(std_dev)

542.32
528.0
75879.5776
275.46247947769587


In [35]:
#62.

arr = np.random.randint(1,100,50)
percentile = np.quantile(arr,[0.25,0.75])
print(percentile)

[20.75 79.  ]


In [36]:
#63.

arr1 = np.random.randint(1,30,3)
arr2 = np.random.randint(1,30,3)

coef = np.corrcoef(arr1,arr2)[0,1]
print(coef)

-0.8183918171270463


In [37]:
#64.

mat1 = np.random.randint(1,3,(3,3))
mat2 = np.random.randint(1,3,(3,3))
np.dot(arr1,arr2)

910

In [38]:
#65.

arr = np.random.randint(10,1000,50)
tenth = np.percentile(arr,10)
median = np.median(arr)
ninetieth = np.percentile(arr,90)
quartiles = np.quantile(arr,[0.25,0.75])
print(tenth)
print(median)
print(ninetieth)
print(quartiles)

57.7
461.0
938.0
[235.25 777.5 ]


In [39]:
#66.

arr = np.arange(1,10)
index = np.where(arr == 4)[0]

In [40]:
index

array([3])

In [41]:
#67.

arr = np.array([1,15,2,6,10,18,3,7])
np.sort(arr)

array([ 1,  2,  3,  6,  7, 10, 15, 18])

In [42]:
#68.

arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr>20]
print(filtered)

[25 42 30]


In [43]:
#69.

arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 ==0]
print(filtered)

[12 15]


In [44]:
#70.

arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr>=20) & (arr<=40)]
print(filtered)

[20 30 40]


In [45]:
#71.

arr = np.array([1, 2, 3])
byte = arr.dtype.byteorder
byte

'='

In [46]:
#72.

arr = np.array([1, 2, 3], dtype=np.int32)
swap = arr.byteswap()
swap

array([16777216, 33554432, 50331648], dtype=int32)

In [47]:
#73.

arr = np.array([1, 2, 3], dtype=np.int32)
a = arr.copy()
swap = arr.byteswap()
print(swap)
print(a)

[16777216 33554432 50331648]
[1 2 3]


In [48]:
#75.

arr = np.array([1, 2, 3], dtype=np.int32)

is_needed = arr.dtype.byteorder == '<'
print('Byte swapping necessary',is_needed)

Byte swapping necessary False


In [49]:
#76.

arr1 = np.arange(1,10,1)
copy_arr = arr1

print(arr1)
print(copy_arr)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [50]:
copy_arr[2] = 4
print(arr1)
print(copy_arr)
print('yes changing')

[1 2 4 4 5 6 7 8 9]
[1 2 4 4 5 6 7 8 9]
yes changing


In [51]:
#79.

orig_arr = np.arange(1,9).reshape(2,4)
reshaped = orig_arr.reshape(4,2)
reshaped[2,1] = 89
print('modified reshaped:\n',reshaped)
print('orig arr after modify:\n',orig_arr)

modified reshaped:
 [[ 1  2]
 [ 3  4]
 [ 5 89]
 [ 7  8]]
orig arr after modify:
 [[ 1  2  3  4]
 [ 5 89  7  8]]


In [52]:
#80.

data = np.random.randint(1,10,(3,4))
print('original data:\n',data)

data_copy = data[data>5].copy()
print('elements greater than 5:\n',data_copy)
data_copy[1] = 222
print('modified data_copy:\n',data_copy)

print('oroginal data after modificataion:\n',data)

original data:
 [[4 4 2 3]
 [7 9 7 8]
 [4 9 9 7]]
elements greater than 5:
 [7 9 7 8 9 9 7]
modified data_copy:
 [  7 222   7   8   9   9   7]
oroginal data after modificataion:
 [[4 4 2 3]
 [7 9 7 8]
 [4 9 9 7]]


In [53]:
#81.

mat1 = np.random.randint(1,10,(3,3))
mat2 = np.random.randint(1,20,(3,3))
print(mat1 + mat2)
print(mat1 - mat2)


[[25 23 12]
 [15 16 21]
 [26 26 16]]
[[-13 -15   2]
 [-13  -2 -15]
 [-10  -8   0]]


In [54]:
#82.

C = np.random.randint(1,10,(3,2))
D= np.random.randint(1,20,(2,4))

C@D

array([[136,  71, 175, 159],
       [ 60,  35,  83,  75],
       [ 86,  21,  73,  69]])

In [58]:
#83.

E = np.array([[1,2,3],[5,6,7]])
E.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [61]:
#84.

S = np.random.randint(1,10,(4,4))
determinant = np.linalg.det(S)
print(determinant)

-115.99999999999999


In [62]:
#85.

I = np.random.randint(1,10,(3,3))
inverse = np.linalg.inv(I)
print(inverse)

[[ 1.8  -0.24 -0.64]
 [-0.8   0.04  0.44]
 [-0.6   0.28  0.08]]
