In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#1.


a = [0,1,2,3,4,5]
arr = np.array(a)

In [3]:
arr


array([0, 1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int64')

In [5]:
#2.


arr = np.array([1.5, 2.6, 3.7])

In [6]:
arr.dtype

dtype('float64')

In [7]:
#3.


l = [7,6,7,8,]
arr = np.array((l),dtype =np.complex128)
arr

array([7.+0.j, 6.+0.j, 7.+0.j, 8.+0.j])

In [8]:
#4.


arr1 = np.array([1,2,3,4,5],dtype = np.int64)
arr2 = np.array((arr1),dtype = np.float32)

In [9]:
arr2

array([1., 2., 3., 4., 5.], dtype=float32)

In [10]:
arr2.dtype

dtype('float32')

In [11]:
arr1.dtype

dtype('int64')

In [12]:
#5.

arr = np.array([1,2,3,4,5],dtype = np.float64)

In [13]:
arr

array([1., 2., 3., 4., 5.])

In [14]:
arr1 = np.array((arr),dtype = np.float32)

In [15]:
arr1

array([1., 2., 3., 4., 5.], dtype=float32)

In [16]:
#6.

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape,size,dtype

user_input = input("Enter array elements(separated by spaces):").split()
elements = [int(x) for x in user_input]
array = np.array(elements)
shape,size,dtype = array_attributes(array)

print('shape:',shape)
print('size:',size)
print('dtype:',dtype)

Enter array elements(separated by spaces): 1 2 3


shape: (3,)
size: 3
dtype: int64


In [17]:
#7.

def array_dimension(arr):
    dimension = arr.ndim
    return dimension

user_input = input("Enter array elements(separated by spaces):").split()
elements = [int(x) for x in user_input]
array = np.array(elements)
dimension = array_dimension(array)
print('Dimension:',dimension)

Enter array elements(separated by spaces): 1 2 3 4


Dimension: 1


In [18]:
#8.

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size,total_size

user = input("Enter elemets(separated by space):").split()
elements = [int(x) for x in user]
array = np.array(elements)
item_size,total_size = item_size_info(array)
print('Item size:',item_size)
print('Total size:',total_size)

Enter elemets(separated by space): 1 2 3 4 


Item size: 8
Total size: 32


In [19]:
#9.

def array_strides(arr):
    strides = arr.strides
    return strides

user1 = input("Enter elements(separated by spaces):").split()
elements = [int(x) for x in user1]
array = np.array(elements)
strides = array_strides(array)
print("Strides:",strides)

Enter elements(separated by spaces): 12 3 4 5 6 7


Strides: (8,)


In [20]:
#10.

def shape_stride(arr):
    shape = arr.shape
    stride = arr.strides
    return shape,stride

user2 = input("Enter elements(separated  by spaces):").split()
elements = [int(x) for x in user1]
array = np.array(elements)
shape,stride = shape_stride(array)
print('shape:',shape)
print('stride:',stride)

Enter elements(separated  by spaces): 1 2 3 4 5


shape: (6,)
stride: (8,)


In [22]:
#11.

def zeroes_array(n):
    return np.zeros(n)

n = int(input("enter elements:"))
array = zeroes_array(n)
print('Array:',array)

enter elements: 12


Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
#12.

def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))

rows = int(input("enter row:"))
cols = int(input("enter col:"))
matrix = create_ones_matrix(rows,cols)
print('Matrix:',matrix)

enter row: 12
enter col: 3


Matrix: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#13.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

array = generate_range_array(2,10,1)
print('range array is:',array)

range array is: [2 3 4 5 6 7 8 9]


In [25]:
#14.

def generated_lin_space(start, stop, num):
    return np.linspace(start, stop, num)

array = generated_lin_space(12,45,90)
print("generated array:",array)

generated array: [12.         12.37078652 12.74157303 13.11235955 13.48314607 13.85393258
 14.2247191  14.59550562 14.96629213 15.33707865 15.70786517 16.07865169
 16.4494382  16.82022472 17.19101124 17.56179775 17.93258427 18.30337079
 18.6741573  19.04494382 19.41573034 19.78651685 20.15730337 20.52808989
 20.8988764  21.26966292 21.64044944 22.01123596 22.38202247 22.75280899
 23.12359551 23.49438202 23.86516854 24.23595506 24.60674157 24.97752809
 25.34831461 25.71910112 26.08988764 26.46067416 26.83146067 27.20224719
 27.57303371 27.94382022 28.31460674 28.68539326 29.05617978 29.42696629
 29.79775281 30.16853933 30.53932584 30.91011236 31.28089888 31.65168539
 32.02247191 32.39325843 32.76404494 33.13483146 33.50561798 33.87640449
 34.24719101 34.61797753 34.98876404 35.35955056 35.73033708 36.1011236
 36.47191011 36.84269663 37.21348315 37.58426966 37.95505618 38.3258427
 38.69662921 39.06741573 39.43820225 39.80898876 40.17977528 40.5505618
 40.92134831 41.29213483 41.66292135 

In [27]:
#15.

def create_identity_matrix(n):
    return np.eye(n)

n = int(input("enter size of matrix:"))
matrix = create_identity_matrix(n)

print('identity matrix:',matrix)

enter size of matrix: 12


identity matrix: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [28]:
#16.

def list_array(lis):
    return np.asarray(lis)
lis = [1,2,3,4,5]
arr = list_array(lis)
print('value:',arr)

value: [1 2 3 4 5]


In [29]:
arr.dtype

dtype('int64')

In [30]:
#17.

arr1 = np.array([1,2,3,4,5])
arr2 = arr1.view()
arr2

array([1, 2, 3, 4, 5])

In [31]:
arr2[0] = 20

In [32]:
print('modified arr1:',arr1)
print('modified arr2:',arr2)

modified arr1: [20  2  3  4  5]
modified arr2: [20  2  3  4  5]


In [33]:
#18.

def concatenated_arrays(arr1,arr2,axis=0):
    return np.concatenate((arr1,arr2),axis=axis)

arr1 = np.array([[1,2,3],[4,4,5],[4,5,6]])
arr2 = np.array([[7,8,9],[4,6,8],[1,3,5]])
s = concatenated_arrays(arr1,arr2,axis=0)
print("s:",s)    

s: [[1 2 3]
 [4 4 5]
 [4 5 6]
 [7 8 9]
 [4 6 8]
 [1 3 5]]


In [ ]:
#19.

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([7,8])
arr3 = np.concatenate((arr1,arr2.reshape(1,2)),axis =1)
print(arr3)